forecast_simple:
    path: "/forecast/index"
    defaults: {_controller: AppBundle:Forecast:indexParam}
forecast_param:
    path: "/forecast/{weather}"
    defaults: {_controller: AppBundle:Forecast:indexParam}
